[package]
name = "wsrx-cli"
version = "0.1.0"
edition = "2021"
authors = ["Reverier-Xu <reverier.xu@xdsec.club>"]
description = "Controlled TCP-over-WebSocket forwarding tunnel."

[dependencies]
wsrx = { version = "*", path = "../lib" }
tokio = { version = "1.27", features = ["full"] }
